#include "StyleHelper.h"

QString StyleHelper::getApplicationStyle() {
    return
        "QMainWindow, QDialog, QMessageBox, QStackedWidget, .MonthWidget, .calendar, .TaskWidget, .TagWidget, .AddDialog {"
        "  background-color: #F4EBE1 !important;"
        "  color: #4A3E4D;"
        "  font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, Roboto, sans-serif;"
        "  font-size: 14px;"
        "}"

        "QWidget {"
        "  color: #4A3E4D;"
        "}"

        "QPushButton {"
        "  background-color: #D5A5AA;"
        "  color: #FFFFFF;"
        "  border: none;"
        "  border-radius: 8px;"
        "  padding: 6px 6px;"
        "  font-weight: 600;"
        "  font-size: 14px;"
        "}"
        "QPushButton:hover { background-color: #83A6BF; }"
        "QPushButton:pressed { background-color: #61849D; }"
        "QPushButton:checked { background-color: #7293A9; color: #FFFFFF; }"
        "QPushButton:disabled { background-color: #E2D3CD; color: #A6959B; }"

        "QLineEdit, QDateEdit, QTimeEdit {"
        "  background-color: #FFFFFF;"
        "  color: #4A3E4D;"
        "  border: 1px solid #D1C4B4;"
        "  border-radius: 6px;"
        "  padding: 6px 6px;"
        "}"
        "QLineEdit:focus, QDateEdit:focus, QTimeEdit:focus {"
        "  border: 2px solid #83A6BF;"
        "  padding: 5px 11px;"
        "}"
        "QLineEdit::placeholder { color: #A89A9F; font-style: italic; }"

        "TagComboBox QComboBox {"
        "  background-color: #FFFFFF;"
        "  color: #4A3E4D;"
        "  border: 1px solid #D1C4B4;"
        "  border-radius: 6px;"
        "  padding: 6px 30px 6px 12px;"
        "}"
        "TagComboBox QComboBox:hover { border: 1px solid #83A6BF; }"
        "TagComboBox QComboBox::drop-down {"
        "  subcontrol-origin: padding;"
        "  subcontrol-position: top right;"
        "  width: 25px;"
        "  border-left: 1px solid #E6DBCF;"
        "}"
        "TagComboBox QComboBox QAbstractItemView {"
        "  background-color: #FFFFFF;"
        "  color: #4A3E4D;"
        "  border: 1px solid #D1C4B4;"
        "  border-radius: 6px;"
        "  selection-background-color: #EAB2C2;"
        "  selection-color: #4A3E4D;"
        "  padding: 4px;"
        "}"

        "QCalendarWidget { border: 1px solid #D1C4B4; border-radius: 8px; }"
        "QCalendarWidget QAbstractItemView:enabled {"
        "  background-color: #FFFFFF;"
        "  color: #4A3E4D;"
        "  selection-background-color: #83A6BF;"
        "  selection-color: #FFFFFF;"
        "  border-radius: 0px;"
        "}"
        "QCalendarWidget QAbstractItemView:disabled { color: #C2B6A8; }"
        "QCalendarWidget QWidget#qt_calendar_navigationbar {"
        "  background-color: #D5A5AA;"
        "  border-top-left-radius: 8px;"
        "  border-top-right-radius: 8px;"
        "  border-bottom: 2px solid #C29399;"
        "}"
        "QCalendarWidget QToolButton {"
        "  background-color: transparent;"
        "  color: #FFFFFF;"
        "  font-weight: bold;"
        "  border-radius: 4px;"
        " margin: 4px;"
        "  padding: 2px 8px;"
        "}"
        "QCalendarWidget QToolButton:hover { background-color: rgba(255, 255, 255, 0.25); }"
        "QCalendarWidget QToolButton:pressed { background-color: rgba(0, 0, 0, 0.1); }"
        "QCalendarWidget QWidget { alternate-background-color: #F0E4D8; color: #7D6B7F; }"

        "QListWidget, QTreeWidget {"
        "  background-color: #FFFFFF;"
        "  color: #4A3E4D;"
        "  border: 1px solid #D1C4B4;"
        "  border-radius: 8px;"
        "  padding: 1px;"
        "}"
        "QTreeWidget::item { padding: 1px 1px; border-radius: 1px; margin-bottom: 1px; }"
        "QListWidget::item { padding: 1px 1px; border-radius: 6px; margin-bottom: 1px; }"
        "QListWidget::item:hover, QTreeWidget::item:hover { background-color: #F5E6E8; color: #4A3E4D; }"
        "QListWidget::item:selected, QTreeWidget::item:selected { background-color: #83A6BF; color: #FFFFFF; }"

        "QCheckBox { spacing: 1px; color: #4A3E4D; }"
        "QCheckBox::indicator {"
        "  width: 18px;"
        "  height: 18px;"
        "  border: 2px solid #D1C4B4;"
        "  border-radius: 4px;"
        "  background-color: #FFFFFF;"
        "}"
        "QCheckBox::indicator:hover { border: 1px solid #83A6BF; }"
        "QCheckBox::indicator:checked { background-color: #83A6BF; border: 1px solid #83A6BF; }"

        "QScrollBar:vertical { background: transparent; width: 8px; margin: 0px; }"
        "QScrollBar::handle:vertical { background: #C2B6A8; border-radius: 4px; min-height: 25px; }"
        "QScrollBar::handle:vertical:hover { background: #A69787; }"
        "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical, QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical { background: none; height: 0px; }"
        "QScrollBar:horizontal { background: transparent; height: 8px; }"
        "QScrollBar::handle:horizontal { background: #C2B6A8; border-radius: 4px; }"

        "QHeaderView::section {"
        "  background-color: #D5A5AA;"
        "  color: #FFFFFF;"
        "  border: none;"
        "  padding: 6px;"
        "  font-weight: bold;"
        "  text-align: center;"
        "}"

        "QFrame[frameShape='4'], QFrame[frameShape='5'] { color: #E6DBCF; }"
        "QToolTip {"
        "  background-color: #4A3E4D;"
        "  color: #F4EBE1;"
        "  border: none;"
        "  border-radius: 4px;"
        "  padding: 8px 16px;"
        "}"

        "QLabel {"
        "  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"
        "  font-weight: 300;"
        "}";
}